### ISSUE TITLE
Hook 到 ServerApi.Hooks.NetGetData 上会导致记录不全

### ISSUE THREAD

**Issue by LaoSparrow** [Leader-txt/TerrariaServerPacketMonitor#3]
Hook 到 ServerApi.Hooks.NetGetData 上会导致记录不全

通过反编译 `TerrariaApi.Server.HookManager.InvokeNetGetData ` 得知部分包会被截取
<img width="794" alt="image" src="https://user-images.githubusercontent.com/60737561/210138077-f75a308a-cec7-4a37-a65b-72cd58e3ebcb.png">

考虑转为使用更底层的 `OTAPI.Hooks.MessageBuffer.GetData`

**Comment by Leader-txt** [comment]
I've invited you to join this repository,you can fix it by yourself~

**Comment by LaoSparrow** [comment]
6

**Comment by Leader-txt** [comment]
And you can close this issue by yourself.

**Comment by LaoSparrow** [comment]
fixed in 42b454163b44e7cac563d58fb940dac1d88c3677
